www/backend/models/Lote.php
<?php

namespace backend\models;

use Yii;

/**
 * This is the model class for table "lote".
 *
 * @property integer $id
 * @property integer $paca
 * @property double $precio
 * @property string $calidad
 * @property integer $cantidad
 * @property string $descripcion
 * @property string $creacion
 * @property string $modificacion
 * @property integer $cant_inicial
 * @property integer $imp_ven_i
 *
 * @property Package $paca0
 * @property LotePrecio[] $lotePrecios
 */
class Lote extends \yii\db\ActiveRecord
{
	public $EXENTO = 0;
	public $AGRAVADO = 1;
	
    private $creacion_fecha;    
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'lote';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['paca', 'precio',  'cantidad', 'descripcion', 'creacion', 
            'modificacion', 'cant_inicial','unidad'], 'required'],
            [['paca','imp_ven_i'], 'integer'],
            [['precio','precioCompra','utilidad','minimo','alerta'], 'number'],
            [['cod_barras','cod_inte_producto','cod_prod_proveedor'], 'unique'],
            [['cantidad', 'cant_inicial','minimo','alerta'], 'double'],
            [['calidad', 'descripcion','unidad','cod_barras','cod_provedor_a',
            'cod_inte_producto','cod_prod_proveedor'], 'string'],
            [['creacion', 'modificacion'], 'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('backend', 'ID'),
            'paca' => Yii::t('backend', 'Paca'),
            'precio' => Yii::t('backend', 'Precio de venta'),
            'calidad' => Yii::t('backend', 'Calidad'),
            'unidad' => Yii::t('backend', 'Unidad de medida'),
            'cantidad' => Yii::t('backend', 'Cantidad Actual'),
            'descripcion' => Yii::t('backend', 'Descripcion'),
            'creacion' => Yii::t('backend', 'Creacion'),
            'modificacion' => Yii::t('backend', 'Modificacion'),
            'cant_inicial' => Yii::t('backend', 'Cant Inicial'),
            'impGetText' => Yii::t('backend', 'Impuesto'),
            'cod_provedor_a' => Yii::t('backend', 'Cod Proveedor'),
            'cod_inte_producto' => Yii::t('backend', 'CPI / Código Prod Interno'),
            'cod_prod_proveedor' => Yii::t('backend', 'CPP / Código Prod Proveedor'),
        ];
    }

	 /**
     * @return \yii\db\ActiveQuery
     */
    public function getImpGetText()
    {
        if(isset($this->imp_ven_i))
			if($this->imp_ven_i==1)
				return 'AGRAVADO';
			else
				return 'EXENTO';
		else
			return 'N/D';
    }
	
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPaca0()
    {
        return $this->hasOne(Package::className(), ['id' => 'paca']);
    }
    
    public function getProveedor0()
    {
        return $this->hasOne(Colaborador::className(), ['cod_provedor' => 'cod_provedor']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLotePrecios()
    {
        return $this->hasMany(LotePrecio::className(), ['lote' => 'id']);
    }
    
    
    public function getPrecioVigente(){        
        $precio=  LotePrecio::find()->where(['lote' => $this->id,'vigente'=>'1'])->one();   
        if(empty($precio))
            return 0;
        $this->precio = $precio->costo;
        return $this->precio;
    }
    /*
     * Muestra las fechas en formato d-m-y
     */
    public function VerFechas(){        
        date_default_timezone_set('America/Costa_Rica');
        $this->creacion_fecha=$this->creacion;
        $this->creacion =  date('d-m-Y  H:i:s',strtotime($this->creacion));    
        $this->modificacion =  date('d-m-Y  H:i:s',strtotime($this->modificacion));        
    }
    /*
     * Guarda las fechas en BD con formato Y-m-d
     */
    public function GuardarFechas(){        
        date_default_timezone_set('America/Costa_Rica');
        $this->modificacion =  date('Y-m-d H:i:s',  strtotime('now'));  
        $this->creacion =  $this->creacion_fecha;
              
        if($this->isNewRecord){                    
            $this->creacion =  date('Y-m-d H:i:s',strtotime('now'));                
        }
    }
}

www/backend/controllers/LoteController.php
<?php

namespace backend\controllers;

use Yii;
use backend\models\Lote;
use backend\models\search\LoteSearch;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

use backend\models\LotePrecio;
use yii\web\Response;

/**
 * LoteController implements the CRUD actions for Lote model.
 */
class LoteController extends BaseController
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    public function actionRetirar(){ 
        $i=0;$resultados=[];
        if (isset($_POST["retirar"])) {
            if(trim($_POST["retirar"]['lotes'])!=""){
                $lotes=  explode(',', $_POST["retirar"]['lotes']);               
                foreach ($lotes as $lote){
                    if((int)$lote){
                        $Olote=Lote::findOne($lote);
                        $inicial=$Olote->cantidad;                        
                        $Olote->cantidad-=1;      
                        $Olote->cant_inicial-=1;
                        if($Olote->update()){
                            $resultados[$i]=[
                                'lote'=>$lote,
                                'inicial'=>$inicial,
                                'final'=>$Olote->cantidad,
                                'mns'=>'Correcto'
                                ];
                        }else{
                            $resultados[$i]=[
                                'lote'=>$lote,
                                'inicial'=>$inicial,
                                'final'=>$Olote->cantidad,
                                'mns'=>'NO SE QUITÓ'
                                ];                    
                        }                        
                    }
                    $i++;
                }
            }
        } 
        
        return $this->render('_form_retirar',[
            'resultados'=>$resultados
        ]);       
    }
    /**
     * Lists all Colaborador models.
     * @return mixed
     */
    public function actionCodigo($cod)
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        if($_GET['tipo'] == 'inp_cod_int_lot')
            $model= Lote::findOne(['id'=>"$cod"]);
        else
            $model= Lote::findOne(['cod_inte_producto'=>"$cod"]);
        if($model){
        //$model->precio="Sin precio vigente";   
            /*
            foreach($model->lotePrecios as $precio){
                if($precio->vigente){
                    $model->precio=$precio->costo;
                }
            }
            */
            return $model;
        }else{
            return 0;
        }     
    }
    
    /**
     * Lists all Lote models.
     * @return mixed
     */
    public function actionIndex($id=null)
    {
        if(isset($_GET['loteSet'])){
            $_SESSION['loteSet'] = $_GET['loteSet'];
             return $this->redirect(['/factura/comprobante', 'id' => $_GET['venta']]);
        }
        
        $searchModel = new LoteSearch();
        if((int)$id!==0){
            $searchModel->paca = $id;
        }else{
            $searchModel->paca = null;
        }
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'config'=>$this->config
        ]);
    }

    /**
     * Displays a single Lote model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $model=  $this->findModel($id);
        $model->VerFechas();
        
        return $this->render('view', [
            'model' => $model,
        ]);
    }

    /**
     * Creates a new Lote model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($id)
    {
        $model = new Lote();
        $model->paca=(int)$id;
        $model->calidad='...';
        $model->GuardarFechas();
        if(isset($_GET['venta'])){
            $_SESSION['loteSet'] = $model->id;
        }
        
        if($model->load(Yii::$app->request->post())){
			$model->cant_inicial = $model->cantidad;
            if ($model->validate()) {                
                $model->save();
                
                $precio= new LotePrecio();
                $precio->lote=$model->id;
                $precio->GuardarFechas();
                $precio->usuario=Yii::$app->user->identity->id;
                $precio->piezas=0;
                $precio->vigente="1";
                $precio->descripcion='Precio inicial';
                $precio->costo=$model->precio;
                if($precio->validate()){
                    $precio->save();
                }else{
                     return $this->render('create', [
                        'model' => $model,
                        'config'=>$this->config
                    ]);
                }
                
                if(isset($_GET['venta'])){
                    $_SESSION['loteSet'] = $model->id;    
                    return $this->redirect(['/factura/comprobante', 'id' => $_GET['venta']]);
                }
                return $this->redirect(['view', 'id' => $model->id]);
            }else{
                 return $this->render('create', [
                    'model' => $model,
                    'config'=>$this->config
                ]);
            }        
        } else {
            
            return $this->render('create', [
                'model' => $model,
                'config'=>$this->config
            ]);
        }
    }

    /**
     * Lists all LotePrecio models.
     * @return mixed
     */
    public function actionPrecios($id)
    {
        $dataProvider = new ActiveDataProvider([
            'query' => LotePrecio::find($id),
        ]);
        return $this->renderPartial('index', [
            'dataProvider' => $dataProvider,
        ],false,true);
    }
    
    /**
     * Updates an existing Lote model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {        
        $model = $this->findModel($id);
       // $calidades=  Diccionario::find()->where(['id_taxonomia'=>3])->all();        
        $model->VerFechas();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {            
           /*
			if(isset($_POST['Lote']['precio'])){
				$precios = LotePrecio::find()->where(['lote'=>$model->id])->all();
				foreach ($precios as $prace){
					if($prace->id==(int)$_POST['Lote']['precio']){
						$prace->vigente='1';
					}
					$prace->update();
				}
			}
			*/
            $model->GuardarFechas();
            $model->save();
            if(isset($_GET['venta'])){
                $_SESSION['loteSet'] = $model->id;
                return $this->redirect(['/factura/comprobante', 'id' => $_GET['venta']]);
            }
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
                'config'=>$this->config
            ]);
        }
    }

    /**
     * Deletes an existing Lote model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);
        foreach($model->lotePrecios as $precio){
            $precio->delete();
        }
        $model->delete();

        return $this->redirect(['index','id'=>$model->paca]);
    }

    /**
     * Finds the Lote model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Lote the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Lote::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

www/backend/views/lote/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use common\components\Moneda;
use kartik\select2\Select2;
use yii\helpers\ArrayHelper;
use backend\models\Colaborador;
?>

<div class="lote-form row">
    <div class="col-lg-6">

        <?php $form = ActiveForm::begin(); ?>

        <?php
      

        echo $form->field($model,'id')->textInput(['readonly'=>true]);
          // echo '<label class="control-label">Proveedor</label>';
        echo $form->field($model,'cod_provedor_a')->textInput();
               
        ?><!--
        <table class="table table-striped table-bordered">        
            <tbody>
            <tr data-key="23">
                <td><?php
/*
                echo Select2::widget([
                    'name' => 'Lote[cod_provedor]',
                    'value' => $model->cod_provedor,
                    'data' => ArrayHelper::map(Colaborador::getProveedores(), 'cod_provedor', 'NombreCompleto'),
                    'options' => ['placeholder' => $model->cod_provedor],
                    'pluginOptions' => [
                        'tags' => true,
                        'tokenSeparators' => [',', ' '],
                        'maximumInputLength' => 10
                    ],
                ]);
            
                */
                ?></td>
                <td style="width:30%;">
                    <span><b><a href="/colaborador/create?lote=<?= $model->id; ?>"><span class="glyphicon glyphicon-plus"></span> Agregar proveedor</a></b></span>
                    <br><span>
                    <b>
                    <a href="/colaborador/index?ColaboradorSearch%5Btipo%5D=4&sort=nombre"><span class="glyphicon glyphicon-search"></span> Ver proveedores </a></b>
                    </span>
                </td>
                
            </tr>
            </tbody>
        </table>-->

<?php
        
        
        echo $form->field($model,'cod_barras')->textInput();
        
       
        
          $form->field($model, 'calidad')
          ->dropDownList(
          [
          'PRIMERA'=>'PRIMERA',
          'SEGUNDA'=>'SEGUNDA',
          'TERCERA'=>'TERCERA'
          ],
          ['prompt'=>'Seleccione por favor',
          'onChange'=>'' ]
          ); 
        ?>


        <?php
        echo $form->field($model, 'unidad')
                ->dropDownList(
                        [
                            'kg' => 'Masa ( kg )',
                            'Unid' => 'Cantidad ( Unid )',
                        // 'Longitud'=>'Longitud ( Metro )',
                        // 'Capacidad'=>'Capacidad ( Litro )',
                        // 'Tiempo'=>'Tiempo ( H:M:S )',
                        ]
        );
?>
</div>
<div  class="col-lg-2"> 
<?php
        echo $form->field($model, 'cantidad')->textInput();
        ?>
</div>
<div  class="col-lg-2"> 
<?php
        echo $form->field($model, 'alerta')->textInput()->hint('Alerta amarilla.');
        ?>
</div>
<div  class="col-lg-2"> 
<?php
        echo $form->field($model, 'minimo')->textInput()->hint('Alerta en rojo.');
?>
</div>
<div  class="col-lg-2"> 
<?php
        echo $form->field($model, 'precioCompra')->textInput([
            'onkeyup'=>'cal_precioVenta(this)',
            'tipo'=>'compra',
            'type'=>'number',
            'step'=>'0.1',
            'min'=>0,
        ]);
     ?>
</div>
<div class="col-lg-2"> 
    <?php
        echo $form->field($model, 'utilidad')->textInput([
            'onkeyup'=>'cal_precioVenta(this)',
            'type'=>'number',
            'step'=>'0.1',
            'min'=>0,
            'tipo'=>'utilidad'
        ]);
     ?>
</div>
<div  class="col-lg-2"> 
<?php
   echo $form->field($model, 'imp_ven_i')
                ->dropDownList(
                        [
                            '0' => 'EXENTO',
                            '1' => 'GRAVADO',
                        ],
                        [
                            'onChange'=>'cal_precioVenta(this)',
                            'tipo'=>'iva'
                        ]
        )->label('IVA');
    ?>
       
</div>


<div class="col-lg-6"> 
    
    <div class="form-group field-lote-precio-calc required">

        <input 
            type="number" 
            id="lote-precio-calc" 
            class="form-control" 
            value="<?= $model->precio ?>" 
            onkeyup="cal_precioVenta(this)" 
            step="0.1" 
            min="0" 
            tipo="precio" 
            aria-required="true">
    </div>

    <?php  
        echo $form->field($model, 'precio')->textInput([
            'onkeyup'=>'cal_precioVenta(this)',
            'type'=>'number',
            'step'=>0.1,
            'min'=>0,
            'tipo'=>'precio',
            'class'=>'hidden'
        ])->label(false);
       
       $precioFinal = $model->precio;
       $iva = $precioFinal*0.13;
        
    ?>
    <div class="alert alert-success " role="alert">
        <b>Precio sin IVA: </b> <span id="span_sub_total"><?= $model->precio; ?></span>
        <br>
        <span class="iva_display <?= ($model->imp_ven_i==0)?'hidden':''?>">
            <b>IVA: </b> 
                <span 
                    style="color: red;"
                    id="span_iva">
                        <?= $iva ?>
                </span>
            <br>
            <b>Precio venta final: </b> 
                <span 
                    style="color: blue;"
                    id="span_total_final">
                        <?= $model->precio+$iva ?>
                </span>
        </span>
    </div>
</div>

</div>
<div class="row">
<div  class="col-lg-6"> 

        <?= $form->field($model, 'descripcion')->textarea(['rows' => 6]) ?>

</div>
<div  class="col-lg-12"> 


    <?php
    echo Html::submitButton(
            $model->isNewRecord ? Yii::t('backend', 'Create') : Yii::t('backend', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary',]);
    ?>


</div>
</div>
    <?php ActiveForm::end(); ?>
    <?php $this->registerJsFile('/js/lote.js'); ?> 
    

www/backend/views/lote/_form_retirar.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model backend\models\Lote */

$this->title = Yii::t('backend', 'Retirar Etiquetas');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="lote-create">
    <h1><?= Html::encode($this->title) ?></h1>

    <form id="form-signup" action="/index.php?r=lote%2Fretirar" method="post" role="form">
        <input type="hidden" name="_csrf" value="ZjI2bTJpd1olCk4dRjsEOTFeYgFURA1vFVR/OFkqEhkMewIsai4OHw==">
        <div class="form-group field-signupform-username required">
            <label class="control-label" for="lotes">Anote los códigos entre comas</label>
            <input type="text" id="signupform-username"  class="form-control" name="retirar[lotes]">
            <p class="help-block help-block">ejemplo: 1413,1212,1022</p>
        </div> 
        <div class="form-group">
            <button type="submit" class="btn btn-primary" name="signup-button">Sacar del inventario</button>                
        </div>
    </form>
    <?php if(!empty($resultados)){ ?>
    <h2>Resultado</h2>
    <table class="table table-striped table-bordered">
        <thead>
            <tr><th>Lote</th>
                <th>Cantidad Inicial</th>
                <th>Cantidad Final</th>
                <th>Se quitaron</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($resultados as $resultado){ ?>
            <tr>
                <td><?= $resultado['lote'] ?></td>
                <td><?= $resultado['inicial'] ?></td>
                <td><?= $resultado['final'] ?></td>
                <td><?= $resultado['mns'] ?></td>
            </tr>
            <?php } ?>
        </tbody>
    </table>
    <?php } ?>
</div>

www/backend/views/lote/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\search\LoteSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="lote-search hidden">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'paca') ?>

    <?= $form->field($model, 'precio') ?>

    <?= $form->field($model, 'calidad') ?>

    <?= $form->field($model, 'cantidad') ?>

    <?php // echo $form->field($model, 'descripcion') ?>

    <?php // echo $form->field($model, 'creacion') ?>

    <?php // echo $form->field($model, 'modificacion') ?>

    <?php // echo $form->field($model, 'cant_inicial') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('backend', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('backend', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

www/backend/views/lote/create.php
<?php

use yii\helpers\Html;

$this->title = Yii::t('backend', 'Create').' '.$config['NombreDeLotes'];

$this->params['breadcrumbs'][] = ['label' => Yii::t('backend', 'Inventario'), 'url' => ['lote/index','sort'=>'-id','id'=>0]];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="lote-create">
    <h1><?= Html::encode($this->title) ?></h1>

	<?php 
		$model->imp_ven_i = 0;
	?>
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
</div>

www/backend/views/lote/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

$this->title = Yii::t('backend', $config['NombreDeLotes']);
$this->params['breadcrumbs'][] = ['label' => Yii::t('backend', 'Inventario'), 'url' => ['lote/index','sort'=>'-id','id'=>0]];

$this->params['breadcrumbs'][] = $this->title;
?>
<div class="lote-index">

    <h1><?= Html::encode($this->title) ?></h1>
	
	<p>
		<?= Html::a(Yii::t('backend', 'Nuevo'), ['create','id'=>$_GET["id"]], ['class' => 'btn btn-success']) ?>
	</p>
	
    <?php 
    if($_GET["id"]){
        if((int)$_GET["id"] > 0){ ?>        
            <p>
                <?= Html::a(Yii::t('backend', 'Create Lote'), ['create','id'=>$_GET["id"]], ['class' => 'btn btn-success']) ?>
            </p>
        <?php
        }
    }
        ?>


    <?php 
    
        $acciones = [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{view} {update}',
            ];
        if(isset($_GET['venta'])){
             $acciones = [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{consultar}',
                'buttons'=>[
                       'consultar'=>function($url,$model){ 
                            $btn = '<a href="/lote/index?id=0&venta='.$_GET['venta'].'&loteSet='.$model->id.'#tbl_terminos" > <span class="glyphicon glyphicon-ok"></span></a>';
                        return $btn;						
                    },
                ]
            ];
        }

    echo GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            'id',
            'cod_barras',
            'cod_provedor_a',
            'precio',
			[
				'attribute'=>'imp_ven_i',
				'label'=>'IVA',
				'value'=>function($model){
					if(isset($model->imp_ven_i))
						if($model->imp_ven_i==1)
							return 'GRAVADO';
						else
							return 'EXENTO';
					else
						return 'N/D';
					
				},
				'format'=>'raw'
			],
			'unidad',
          //  'cantidad',
            [
                'attribute' => 'cantidad',
                'label' => 'Vitrina',
                 'contentOptions'=>function($model){
                     $class = [
                            0 => 'success',
                            1 => 'warning',
                            2 => 'danger',
                     ];
                     $id = 0;
                     $actual = $model->cantidad;
                     $minimo = $model->minimo;
                     $alerta = $model->alerta;                     
                     if($actual < $minimo)
                        $id = 2;
                     elseif($actual >= $model->minimo && $actual <= $alerta)
                        $id = 1;
                     
                     return [
                        'style' => 'width: 10%;text-align:left',
                        'class' => $class[$id]
                    ];
                 },
                'value' => function($model){
                    if($model->unidad == 'mL')
                        return ($model->cantidad/40).' tragos';
                        
                   return $model->cantidad.' '.$model->unidad;                      
                }
            ],
            
             'descripcion:ntext',

            $acciones
            ,
        ],
    ]); ?>

    
    
    
</div>

www/backend/views/lote/update.php
<?php

use yii\helpers\Html;


$this->title = Yii::t('backend', 'Update');
//$this->params['breadcrumbs'][] = ['label' => Yii::t('backend', 'Todas las pacas'), 'url' => ['package/index']];
$this->params['breadcrumbs'][] = ['label' => Yii::t('backend', 'Paca').' '.$model->paca, 'url' => ['index','id'=>$model->paca]];
$this->params['breadcrumbs'][] = ['label' => 'Lote '.$model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="lote-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

www/backend/views/lote/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model backend\models\Lote */

$this->title = 'Lote '.$model->id;
$this->params['breadcrumbs'][] = ['label' => Yii::t('backend', 'Inventario'), 'url' => ['lote/index','sort'=>'-id','id'=>0]];
//$this->params['breadcrumbs'][] = ['label' => Yii::t('backend', 'Lotes'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="lote-view">
<?php  if(Yii::$app->user->identity){
    if(Yii::$app->user->identity->rol_id===3){ ?>
    <p>
        <?= Html::a(Yii::t('backend', 'Update'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('backend', 'Delete'), ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('backend', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>
<?php }else{ ?>
    <h1>Consulta del <?php echo $this->title; ?></h1>
<?php } } ?>
    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'proveedor0.NombreCompleto',
            'cod_barras',
          //  'paca',
            'precio',
			'impGetText:ntext',
          //  'calidad:ntext',
			'unidad',
            'cantidad',
            'alerta',
            'minimo',
            'descripcion:ntext',
            'creacion',
            'modificacion',
        ],
    ]) ?>
    <h2><?= Yii::t('backend','Precios') ?></h2>
    <ol>
        <?php foreach ($model->lotePrecios as $precio) { 
            date_default_timezone_set('America/Costa_Rica');
            $fecha =  date('d-m-Y',strtotime($precio->fecha));  
            $vigente=($precio->vigente==1)?'  <strong> [Precio vigente]</strong>':'';
            ?>
        <li><?= '&#162;'.$precio['costo'].':  Creado el '.$fecha .' por '.$precio->usuario0->username.$vigente; ?> </li>
         <?php }?>
    </ol>

</div>