www/backend/controllers/ReporteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use common\models\LoginForm;
use yii\filters\VerbFilter;
use common\models\AccessHelpers;
use backend\models\search\FacturaSearch;
use yii2tech\spreadsheet\Spreadsheet;
use yii\data\ArrayDataProvider;
use backend\models\VentasDiarias;
use backend\models\search\VentasDiariasSearch;

use backend\models\Factura;
/**
 * Reportes controller
 */
class ReporteController extends BaseController
{
    
    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    
    public function actionIndex(){
         return $this->render('index');
    }
    //Hoy por defecto 
    //Desde - Hasta
    //d-m-y      
    public function actionDiarioDetalle(){       
        return $this->render('diario-detalle',[
            'config'=>$this->config
        ]);
    }
    public function actionDiarioResumen(){
        return $this->render('diario-resumen',[
            'config'=>$this->config
        ]);
    }
    
    //Mes actual por defecto
    //Desde - Hasta
    //m-y
    public function actionMesDetalle(){
        return $this->render('mes-detalle',[
            'config'=>$this->config
        ]);
    }

    //Año actual por defecto
    //Desde - Hasta
    //y    
    public function actionMesResumen(){
        //seleccionar el ultimo registro de dia resumido
        //Calcular los dias resumidos
        //Presentar reporte
        
        VentasDiarias::GenerarResumen();
        $searchModel = new VentasDiariasSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('mes-resumen',[
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'config'=>$this->config,
        ]);
    }
    
    public function actionAnualDetalle(){
        echo 'Anual';
    }
    
    public function actionToExcel(){
        $searchModel = new FacturaSearch();
        $dataProvider = $searchModel->diarioDeVentas(Yii::$app->request->queryParams);
        
        $exporter = new Spreadsheet([
            'dataProvider' => $dataProvider,
            'columns' => [
                'fecha',
                
                [
                    'attribute'=>'receptorNombre',
                    'value'=>function($model){
                        return $model->getReceptorNombre();   
                    }
                ],
                'comprobante.numConce',
                'receptorCedula',
                'receptorNombre',
                'dgt_gravado',
                'dgt_totExento',
                'dgt_totDescuento',
                'dgt_totImpuesto',
                'dgt_total',
                
            ],
        ]);             
        $exporter->save(Yii::getAlias('@webroot').'/fileexcel.xls');
    }
    
    public function actionDiarioDeVentas()
    {            
        return $this->render('diario-de-ventas',['config'=>$this->config]);     
    }
    
    public function actionDiarioDeVentasPersonalizado()
    {
        $searchModel = new FacturaSearch();
        $dataProvider = $searchModel->diarioDeVentas(Yii::$app->request->queryParams);
           
        return $this->render('diario-de-ventas-personalizado', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);     
    }
}

www/backend/views/reporte/_desde.php
 <?php
    use backend\models\Factura;
    use yii\helpers\Html;
    use yii\bootstrap\ActiveForm;
    use dosamigos\datepicker\DatePicker;


    $form = ActiveForm::begin();
        
        $model = new backend\models\Factura();
        if(isset($_POST['Factura'])){            
            if(isset($_POST['Factura']['desde'])){
                $model->desde = $_POST['Factura']['desde'];                
            }else{
                $model->desde = date('Y-m-d', strtotime('now'));
            } 
         }
        ?>
        <div class="col-lg-2">
        <?php
            echo Html::label('Fecha');
            echo DatePicker::widget([
                'model' => $model,
                'attribute' => 'desde',
                'language' => 'es',
                'clientOptions' => [
                    'autoclose' => true,
                    'format' => 'yyyy-mm-dd',
                ]
            ]); ?>
        </div> 
              

        <div class="col-lg-2">
        <?php
            echo Html::label('Accion');
        ?>
            <div class="form-group">
                <?= Html::submitButton(Yii::t('app', 'Enviar'), ['class' => 'btn btn-primary']) ?>
            </div>
        </div>
                
    <?php ActiveForm::end(); ?>

www/backend/views/reporte/_desdehasta.php
 <?php
    use backend\models\Factura;
    use yii\helpers\Html;
    use yii\bootstrap\ActiveForm;
    use dosamigos\datepicker\DatePicker;


    $form = ActiveForm::begin();
        
        $model = new backend\models\Factura();
        if(isset($_POST['Factura'])){
            if(isset($_POST['Factura']['desde'])){
                $model->desde = $_POST['Factura']['desde'];
            }else{
                $model->desde=date('Y-m-', strtotime('now'));
                $model->desde.='01';
            } 
            
            if(isset($_POST['Factura']['hasta'])){
                $model->hasta = $_POST['Factura']['hasta'];
            }else{
                $model->hasta = date('Y-m-', strtotime('now'));
                $model->hasta .= '31';
            } 
         }
         
        ?>
        <div class="col-lg-2">
        <?php
            echo Html::label('Desde');
            echo DatePicker::widget([
                'model' => $model,
                'attribute' => 'desde',
                'language' => 'es',
                'clientOptions' => [
                    'autoclose' => true,
                    'format' => 'yyyy-mm-dd',
                ]
            ]); ?>
        </div> 
        <div class="col-lg-2">
        <?php
            echo Html::label('Hasta');
            echo DatePicker::widget([
                'model' => $model,
                'attribute' => 'hasta',
                'language' => 'es',
                'clientOptions' => [
                    'autoclose' => true,
                    'format' => 'yyyy-mm-dd',
                ],
            ]); 
        ?>
        </div>
        

        <div class="col-lg-2">
        <?php
            echo Html::label('Accion');
        ?>
            <div class="form-group">
                <?= Html::submitButton(Yii::t('app', 'Enviar'), ['class' => 'btn btn-primary']) ?>
            </div>
        </div>
                
    <?php ActiveForm::end(); ?>

www/backend/views/reporte/_hoy_tr_resumen.php
<?php
    use common\components\Moneda;
?>
<tr>
    <td class=""><?= $titulo ?></td>                      
    <td><?= Moneda::get($monto); ?></td>
</tr> 

www/backend/views/reporte/_lista.php
<?php

    use kartik\grid\GridView;
    use common\components\Botones;
    use common\components\Moneda;
    use backend\models\CodigosComprobantes;
    

 echo GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'showPageSummary' => true,
        'layout' => '
            <div class="row">
                <div class="col-xs-12">
                    <div class="text-right">
                        {export}{toggleData}
                    </div>
                </div>
            </div>
            {items}{pager}',
            'exportConfig' => [
                GridView::PDF => [],
                GridView::EXCEL => [],
            ],
        'columns' => [
                   //['class' => 'yii\grid\SerialColumn'],
                   [
                        'attribute' => 'concecutivo',
                        'contentOptions' => ['style' => 'width: 8%;text-align:left'],
                        'value'=>function($model){
                            return $model->comprobante->numConce;
                        }
                    ], /*
                    [
                        'label'=>'ID File',
                        'contentOptions' => ['style' => 'width: 8%;text-align:left'],
                        'value'=>function($model){
                            return $model->comprobante->id;
                        }
                    ],
                     [
                        'label'=>'ID Comprobante',
                        'contentOptions' => ['style' => 'width: 8%;text-align:left'],
                        'value'=>function($model){
                            return $model->comprobante->idComprobante;
                        }
                    ],
                    [
                        'attribute' => 'Estado',
                        'contentOptions' => ['style' => 'width: 8%;text-align:left'],
                        'value'=>function($model){
                            return $model->comprobante->estadoEstado;
                        }
                    ],*/
                    [
                        'attribute' => 'fecha',
                        'contentOptions' => ['style' => 'width: 8%;text-align:left'],
                    ],
                    [
                        'label' => 'Receptor',
                        'contentOptions' => ['style' => 'width: 16%;text-align:left'],
                        'attribute' => 'colaborador_nombre',
                        'format' => 'raw',
                        'value' => function ($model, $key, $index) {
                            return $model->receptores;
                        },                      
                    ],
                    [
                        'attribute'=>'dgt_medioPago',
                        'label'=>'Medio',
                        'contentOptions' => ['style' => 'width: 5%;text-align:left'],
                        'value'=>function($model){
                            return CodigosComprobantes::MEDIOSDEPAGO[$model->dgt_medioPago];   
                        }                        
                    ],
                    [
                    'attribute'=>'dgt_gravado',
                    'label'=>'Gravado',
                    'contentOptions' => ['style' => 'width: 5%;text-align:left'],
                    'pageSummary' => true,
                    'value' => function($model){
                            return Moneda::getreporte($model->dgt_gravado);
                        }
                    ],
                    [
                    'attribute'=>'dgt_totExento',
                    'label'=>'Exento',
                    'contentOptions' => ['style' => 'width: 5%;text-align:left'],
                    'pageSummary' => true,
                    'value' => function($model){
                            return Moneda::getreporte($model->dgt_totExento);
                        }
                    ],
                    [
                    'attribute'=>'dgt_totDescuento',
                    'label'=>'Descuentos',
                    'contentOptions' => ['style' => 'width: 5%;text-align:left'],
                    'pageSummary' => true,
                    'value' => function($model){
                            return Moneda::getreporte($model->dgt_totDescuento);
                        }
                    ],
                    
                    [
                    'attribute'=>'dgt_totImpuesto',
                    'label'=>'Impuestos',
                    'contentOptions' => ['style' => 'width: 5%;text-align:left'],
                    'pageSummary' => true,
                    'value' => function($model){
                            return Moneda::getreporte($model->dgt_totImpuesto);
                        }
                    ],
                    [
                    'attribute'=>'dgt_total',
                    'pageSummary' => true,
                    'value' => function($model){
                            return Moneda::getreporte($model->dgt_total);
                        }
                    ],              
                    [
                        'label' => 'Consultar',
                        'format' => 'raw',
                        'value' => function($model) {
                            return Botones::Consultar('/factura/comprobante',"id={$model->id}",'Consultar');
                        },
                    ],
                ],
            ]);
            ?>

www/backend/views/reporte/deducibles-detalle.php
<?php
   
    use backend\models\Caja;
    use backend\models\Factura;
    use backend\models\search\FacturaSearch;
    use common\components\Moneda;
    use kartik\grid\GridView;
    use common\components\Botones;
    use backend\models\CodigosComprobantes;
    
                  
    $this->title = 'Reporte de gastos deducibles';     
    $this->params['breadcrumbs'][] = ['label' => 'Reportes', 'url' => ['/reporte/index']];
    $this->params['breadcrumbs'][] = $this->title;
   
        
     ?>
  
 
        <div class="col-lg-12">

        <h1><?php echo $this->title; ?></h1>
        <p>
            Reporte de todas los gastos realizados entre las fechas seleccionadas.
        </p>
        </div>
    <?= $this->render('_desdehasta') ?>
         <div class="col-lg-12">
         
         <?php
         
          echo GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,       
        'showPageSummary' => true,
        'layout' => '
            <div class="row">
                <div class="col-xs-12">
                    <div class="text-right">
                        {export}{toggleData}
                    </div>
                </div>
            </div>
            {items}{pager}',
            'exportConfig' => [
                GridView::PDF => [],
                GridView::EXCEL => [],
            ],
        'columns' => [
           // ['class' => 'yii\grid\SerialColumn'],

         //   'id',
            'numeroConcecutivo:ntext',
          //  'tipoComprobante:ntext',
            'clave:ntext',
          //  'numeroCedulaEmisor:ntext',
            'fechaEmisionDoc',
            // 'mensaje',
             'detalleMensaje',
              [
                'label' => 'FE Envio',
                'contentOptions' => function($model) {
                    $clases = [
                        100 => 'info',
                        200 => 'success',
                        300 =>'warning', 
                        400 => 'danger',
                        500  => 'danger', 
                        0  => 'warning', 
                    ];
                    $id = $model->getClase();
                    
                    return [
                        'class' => $clases[$id],
                        'code' => $id
                        ];
                },
                    'format' => 'raw',
                    'value' => function($model) {
                            return CodigosComprobantes::ESTADOENTREGA[$model->getClase()];
                        },
                    ],
                /*
                 [
                        'label' => 'FE Estado',
                        'format' => 'raw',
                        'contentOptions' => function($model) {
                            $clases = [
                            0 => 'warning', 
                            1 => 'success', 
                            2 => 'danger', 
                            3 => 'danger', 
                            800 => 'danger',
                            100 => 'info',
                            200 => 'success',
                            300 =>'warning', 
                            400 => 'danger',
                            500  => 'danger',
                            null => 'warning'
                            ];
                            $id = $model->getClaseEstado();
                            return [
                                'class' => $clases[$id],
                                'code' => $id
                            ];
                        },
                        'value' => function($model) {                            
                            return CodigosComprobantes::ESTADOVALIDACION[$model->getClaseEstado()];
                        },
                    ],
                    */
                    [
                        'pageSummary' => true,
                        'attribute'=>'totalFactura',
                        'label'=>'Total',
                    ],
        ],
            ]);
            
         
        
        
         ?>
        
        </div>

                   
        
           

www/backend/views/reporte/diario-detalle.php
<?php
   
    use backend\models\Caja;
    use backend\models\Factura;
    use backend\models\search\FacturaSearch;
    use common\components\Moneda;
                  
    $model = new Factura();
    $this->title = 'Detalles diarios';
    $model->desde = date('Y-m-d', strtotime('now'));
    $model->hasta = date('Y-m-d', strtotime('now'));
    $searchModel = new FacturaSearch();
    $dataProvider = $searchModel->diarioDeVentasTipo('hoy');
    
    $this->params['breadcrumbs'][] = ['label' => 'Reportes', 'url' => ['/reporte/index']];
$this->params['breadcrumbs'][] = $this->title;
   
        
     ?>
  
 
        <div class="col-lg-12">

        <h1><?php echo $this->title; ?></h1>
        <p>
            Reporte de las ventas diarias, cada linea es una venta efectuada.<br>
            Puedes exportar utilizando el componente superior derecho de la tabla.
        </p>
        </div>
        
        <?php
         echo $this->render('_desdehasta');
        ?>
        
        <div class="col-lg-12">
           <?= $this->render('_lista',[
                    'dataProvider' => $dataProvider,
                    'searchModel' => $searchModel,
            ]) ?>
        
        </div>

                   
        
           

www/backend/views/reporte/diario-resumen.php
<?php

use backend\models\Caja;
use backend\models\Factura;
use backend\models\search\FacturaSearch;
use common\components\Moneda;


                
   
    $this->title = 'Resumen diario';    
    $this->params['breadcrumbs'][] = ['label' => 'Reportes', 'url' => ['/reporte/index']];
$this->params['breadcrumbs'][] = $this->title;
   
        
     ?>
  
 
    <div class="row">
        <div class="col-lg-12">

            <h1><?php echo $this->title; ?></h1>

        </div>
    </div>
    
    <div class="row">
        <?= $this->render('_desde'); ?> 
    </div>
       
        <?php
            $hoy = date('Y-m-d',strtotime('now'));
            
            if(isset($_POST['Factura']['desde'])){
                $hoy = $_POST['Factura']['desde'];
            }
               
            
              /*
               
                $caja = Caja::find()->where(['like','fecha',$hoy])->
                andWhere(['tipo'=>'Abrir'])->one();
                $cajas = [1=>['A'=>0,'C'=>0]];

                if(!empty($caja))
                    $cajas[1]['A'] = $caja->total;
                

                $caja = Caja::find()->where(['like','fecha',$hoy])->
                andWhere(['=','tipo','Cerrar'])->one();

                if(!empty($caja))
                    $cajas[1]['C'] = $caja->total;
*/

                $facturasDeHoy =Factura::find()
                ->where(['like','fecha',$hoy])->
                andWhere(['estado'=>'Facturada'])->all();
                
                /*
                    '01'=>'Efectivo',
                    '02'=>'Tarjeta',
                    '03'=>'Cheque',
                    '04'=>'Transferencia - depósito bancario',
                */

                $tots = [
                    'sg'=>0,
                    'mg'=>0,
                    'tg'=>0,
                    'se'=>0,
                    'me'=>0,
                    'te'=>0,
                    'de'=>0,
                    'im'=>0,
                    'to'=>0
                ];

                $totales = [
                    'USD'=>[
                        '01'=>$tots,
                        '02'=>$tots,
                        '03'=>$tots,
                        '04'=>$tots,
                        'sg'=>0,
                        'mg'=>0,
                        'tg'=>0,
                        'se'=>0,
                        'me'=>0,
                        'te'=>0,
                        'de'=>0,
                        'im'=>0,
                        'to'=>0
                    ],
                    'CRC'=>[
                        '01'=>$tots,
                        '02'=>$tots,
                        '03'=>$tots,
                        '04'=>$tots,
                        'sg'=>0,
                        'mg'=>0,
                        'tg'=>0,
                        'se'=>0,
                        'me'=>0,
                        'te'=>0,
                        'de'=>0,
                        'im'=>0,
                        'to'=>0
                    ]
                ];
                $total = 0;
                foreach($facturasDeHoy as $fact){
                    $totales[$fact->dgt_moneda][$fact->dgt_medioPago]['to'] += $fact->dgt_total	;

                    $totales[$fact->dgt_moneda]['sg'] += $fact->dgt_serviciosGravados;
                    $totales[$fact->dgt_moneda]['mg'] += $fact->dgt_mercaGravada;
                    $totales[$fact->dgt_moneda]['tg'] += $fact->dgt_gravado;

                    $totales[$fact->dgt_moneda]['se'] += $fact->dgt_serviciosExentos;
                    $totales[$fact->dgt_moneda]['me'] += $fact->dgt_mercaExenta;
                    $totales[$fact->dgt_moneda]['te'] += $fact->dgt_totExento;

                    $totales[$fact->dgt_moneda]['de'] += $fact->dgt_totDescuento;
                    $totales[$fact->dgt_moneda]['im'] += $fact->dgt_totImpuesto;
                    $total += $fact->dgt_total;
                }
                ?>
     
     
    <div class="row">
        <div class="col-lg-5" id="resumen_dia">
            <table class="table table-results">
                <tbody>
                <thead>
                    <tr>
                        <th class="">Detalle</th>
                        <th class="">Monto</th>
                    </tr>
                </thead>
                
                    <tr>
                        <td class="">Cantidad de ventas</td>                      
                        <td><?= count($facturasDeHoy) ?></td>
                    </tr> 


                  
                    <?= $this->render('_hoy_tr_resumen',[
                        'titulo'=>'Efectivo',
                        'monto'=>$totales['CRC']['01']['to']
                    ]) ?>

                    <?= $this->render('_hoy_tr_resumen',[
                        'titulo'=>'Tarjeta',
                        'monto'=>$totales['CRC']['02']['to']
                    ]) ?>

                    <?= $this->render('_hoy_tr_resumen',[
                        'titulo'=>'Cheques',
                        'monto'=>$totales['CRC']['03']['to']
                    ]) ?>

                    <?= $this->render('_hoy_tr_resumen',[
                        'titulo'=>'Transferencias',
                        'monto'=>$totales['CRC']['04']['to']
                    ]) ?>

                </tbody>
                <tfoot>
                    <?= $this->render('_hoy_tr_resumen',[
                        'titulo'=>'Total Gravado',
                        'monto'=>$totales['CRC']['tg']
                    ]) ?>

                    <?= $this->render('_hoy_tr_resumen',[
                        'titulo'=>'Total Exento',
                        'monto'=>$totales['CRC']['te']
                    ]) ?>

                    <?= $this->render('_hoy_tr_resumen',[
                        'titulo'=>'Total Descuentos',
                        'monto'=>$totales['CRC']['de']
                    ]) ?>

                    <?= $this->render('_hoy_tr_resumen',[
                        'titulo'=>'Total Impuestos',
                        'monto'=>$totales['CRC']['im']
                    ]) ?>

                    <?= $this->render('_hoy_tr_resumen',[
                        'titulo'=>'Total ventas',
                        'monto'=>$total
                    ]) ?>
                        
                
                </tfoot>
            </table>
                
        </div>
    </div>
            <a 
            class="btn btn-warning" 
            href="#" onclick="factura_imprimir('resumen_dia')">Imprimir resumen</a>

        <script>
            function factura_imprimir(id) {
                var ventimp = window.open(' ', 'popimpr');
                ventimp.document.write($("#"+id).html());
                ventimp.document.close();
                ventimp.print();
                ventimp.close();
            }
        </script>

www/backend/views/reporte/mes-detalle.php
<?php
   
    use backend\models\Caja;
    use backend\models\Factura;
    use backend\models\search\FacturaSearch;
    use common\components\Moneda;
                  
    $model = new Factura();
    $this->title = 'Todas las ventas del mes';
    $model->desde = date('Y-m-d', strtotime('now'));
    $model->hasta = date('Y-m-d', strtotime('now'));
    $searchModel = new FacturaSearch();
    $dataProvider = $searchModel->diarioDeVentasTipo('mes');
    
    $this->params['breadcrumbs'][] = ['label' => 'Reportes', 'url' => ['/reporte/index']];
$this->params['breadcrumbs'][] = $this->title;
   
        
     ?>
  
 
        <div class="col-lg-12">

        <h1><?php echo $this->title; ?></h1>
        <p>
            Reporte de todas las ventas realizadas en el mes, cada linea es una venta efectuada.<br>
            Puedes exportar utilizando el componente superior derecho de la tabla.
        </p>
        </div>
    <?= $this->render('_desdehasta') ?>
         <div class="col-lg-12">
           <?= $this->render('_lista',[
                    'dataProvider' => $dataProvider,
                    'searchModel' => $searchModel,
            ]) ?>
        
        </div>

                   
        
           

www/backend/views/reporte/mes-resumen.php
<?php

use yii\helpers\Html;
use kartik\grid\GridView;
use common\components\Botones;
use common\components\Moneda;
use backend\models\CodigosComprobantes;



$this->title = 'Ventas mensuales x dia';
$this->params['breadcrumbs'][] = ['label' => 'Reportes', 'url' => ['/reporte/index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="ventas-diarias-index">

<h1><?= Html::encode($this->title) ?></h1>
     
 <?= $this->render('_desdehasta') ?>
            
<?php
 echo GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'showPageSummary' => true,
        'layout' => '
            <div class="row">
                <div class="col-xs-12">
                    <div class="text-right">
                        {export}{toggleData}
                    </div>
                </div>
            </div>
            {items}{pager}',
            'exportConfig' => [
                GridView::PDF => [],
                GridView::EXCEL => [],
            ],
        'columns' => [
           // ['class' => 'yii\grid\SerialColumn'],

           // 'id',
            'fecha:ntext',
           // 'condicion',
           // 'medioPago',
           // 'tipoCambio',
            //'totGravado',
            
            [
                'label' => 'Exento',
                'format' => 'raw',
                'value' => function($model) {
                     return $model->moneda_reporte($model->totExento);
                },
                'pageSummary' => true,
               
            ], 
            [
                'label' => 'Gravado',
                'format' => 'raw',
                'value' => function($model) {
                     return $model->moneda_reporte($model->totGravado);
                },
                'pageSummary' => true,
               
            ],
            [
                'label' => 'Descuento',
                'format' => 'raw',
                'value' => function($model) {
                     return $model->moneda_reporte($model->totDescuento);
                },
               'pageSummary' => true,
            ],            
            [
                'label' => 'Impuesto',
                'format' => 'raw',
                'value' => function($model) {
                     return $model->moneda_reporte($model->totImpuesto);
                },
               'pageSummary' => true,
            ],
            [
                'label' => 'Total',
                'format' => 'raw',
                'value' => function($model) {
                     return $model->moneda_reporte($model->total);
                },
               'pageSummary' => true,
            ]
            //['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
</div>