www/backend/models/Package.php
<?php

namespace backend\models;
use common\components\Moneda;
use Yii;
/**
 * This is the model class for table "package".
 *
 * @property integer $id
 * @property string $categoria
 * @property string $compra
 * @property string $desempacada
 * @property string $proveedor
 * @property string $estado
 * @property double $precio
 * @property string $calidad
 * @property string $descripcion
 * @property string $creacion
 * @property string $modificacion
 * @property integer $num_factura
 */
class Package extends \yii\db\ActiveRecord
{   
    public $cantPacas;
    public $creacion_fecha;
    //public $ValorDeVenta=0;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'package';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['categoria', 'compra', 'desempacada', 'proveedor', 'estado', 'precio', 'calidad', 'descripcion', 'creacion', 'modificacion', 'num_factura'], 'required'],
            [['categoria', 'proveedor', 'estado', 'calidad', 'descripcion'], 'string'],
            [['compra', 'desempacada', 'creacion', 'modificacion'], 'safe'],
            [['precio'], 'number'],
            [['num_factura'], 'integer']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('backend', 'ID'),
            'categoria' => Yii::t('backend', 'Categoria'),
            'compra' => Yii::t('backend', 'Compra'),
            'desempacada' => Yii::t('backend', 'Desempacada'),
            'proveedor' => Yii::t('backend', 'Proveedor'),
            'estado' => Yii::t('backend', 'Estado'),
            'precio' => Yii::t('backend', 'Costo Compra'),
            'calidad' => Yii::t('backend', 'Calidad'),
            'descripcion' => Yii::t('backend', 'Descripcion'),
            'creacion' => Yii::t('backend', 'Creacion'),
            'modificacion' => Yii::t('backend', 'Modificacion'),
            'ValorDeVenta' => Yii::t('backend', 'Vendido'),
            'ValorDeTienda' => Yii::t('backend', 'En Tienda'),
            'ValorDeVentaInt' => Yii::t('backend', 'Vendido'),
            'num_factura' => Yii::t('backend', 'Num Factura'),
        ];
    }
    /**
     * @return \yii\db\ActiveQuery
     */
    
        
    public function getLaCalidad()
    {
        return $this->hasOne(Diccionario::className(), ['id' => 'calidad']);
    }
               
    public function getElEstado()
    {
        return $this->hasOne(Diccionario::className(), ['id' => 'estado']);
    }        
    public function getLaCategoria()
    {
        return $this->hasOne(Diccionario::className(), ['id' => 'categoria']);
    }    
    public function getElProveedor()
    {
        return $this->hasOne(Colaborador::className(), ['id' => 'proveedor']);
    }       
    public function getLotes(){
        return $this->hasMany(Lote::className(), ['paca' => 'id']);
    }    

	public function getValorDeVenta(){
            $data=$this->lotes;
            $this->cantPacas=count($data);
            $cost=0;
            foreach ($data as $dat){
                $cost+=$dat->precio*($dat->cant_inicial-$dat->cantidad);
            }
            return $cost;
    }   
	
	public function getValorDeVentaInt(){
            $data=$this->lotes;
            $this->cantPacas=count($data);
            $cost=0;
            foreach ($data as $dat){
                $cost += $dat->precio*($dat->cant_inicial-$dat->cantidad);
            }
            return $cost;
    }   
	
	public function getValorDeTienda(){
            $data=$this->lotes;
            $this->cantPacas=count($data);
            $cost=0;
            foreach ($data as $dat){
                $cost+=$dat->precio*$dat->cantidad;
            }
            return $cost;
    }
	
    public function getNombre(){
        $calidad=$this->laCalidad();        
        $categoria=$this->laCategoria();        
        $cod=$this->id();        
        $compra=$this->compra();
    }
	
    
    
    
    /*
     * Muestra las fechas en formato d-m-y
     */
    public function VerFechas(){        
        date_default_timezone_set('America/Costa_Rica');
        $this->compra =  date('d-m-Y',strtotime($this->compra));
        $this->creacion_fecha=$this->creacion;    
        $this->desempacada =  date('d-m-Y',strtotime($this->desempacada));        
    }
    /*
     * Guarda las fechas en BD con formato Y-m-d
     */
    public function GuardarFechas(){        
        date_default_timezone_set('America/Costa_Rica');
        $this->compra =  date('Y-m-d',strtotime($this->compra)); 
        $this->desempacada =  date('Y-m-d',strtotime($this->desempacada));      
        $this->modificacion =  date('Y-m-d',  strtotime('now'));
        $this->creacion =  $this->creacion_fecha;  
              
        if($this->isNewRecord){                   
            $this->creacion =  date('Y-m-d',strtotime('now'));                
        }
    }
}

www/backend/controllers/CrmController.php
<?php
namespace backend\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use common\models\LoginForm;
use yii\filters\VerbFilter;
use common\models\AccessHelpers;
use backend\models\search\FacturaSearch;
use backend\models\Factura;
use backend\models\CrmOportunidades;
use backend\models\search\CrmOportunidadesSearch;
use yii\web\NotFoundHttpException;
use yii\web\Response;

/**
 * CRM controller
 */
class CrmController extends BaseController
{
    
    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionCambiarEtapa($ids,$etapa){
        Yii::$app->response->format = Response::FORMAT_JSON;
        $errors = [];
        foreach (CrmOportunidades::find()->where(['in','id',$ids])->all() as $oportunidad){
            $oportunidad->etapa = $etapa;
            if(!$oportunidad->save()){
                return [
                    'message' => 'Error al modificar',
                    'code' => 304,
                    'data'=>$oportunidad->errors
                ];
            }
        }
        return [
                'message' => 'Oportunidades modificadas',
                'code' => 200,
            ];
        
    }

    public function actionSetTab(){
         $_SESSION['tab_crm'] = $_POST['tab'];
    }
    
    public function actionPanel()
    {
        $data = CrmOportunidades::porPrioridad();
        $searchModel = new CrmOportunidadesSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
                  
        return $this->render('panel', [
            'datos' => $data,
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider
        ]);     
    }

    /**
     * Creates a new CrmOportunidades model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new CrmOportunidades();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['panel']);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing CrmOportunidades model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
             return $this->redirect(['panel']);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing CrmOportunidades model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the CrmOportunidades model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return CrmOportunidades the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = CrmOportunidades::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

www/backend/views/crm/_ficha_oportunidad.php
              
                

        
               
<?php 
use common\components\Moneda;


if(isset($model)){ ?>

            <div class="row opo_sort" data-id="<?= $model->id ?>">
                <div class="col-sm-8">
                   <span id="item_<?= $model->id ?>_nombre"><?= $model->nombre ?></span><span id="item_<?= $model->id ?>_cliente">
                   <br>
                    <a href="/colaborador/view?id=<?= $model->cliente ?>"><?= $model->cliente0->nombre.' '.$model->cliente0->apellido ?></a></span>
                   <br>
                   <span id="item_<?= $model->id ?>_precio">
                     <?= Moneda::gettm($model->monto,'$') ?>
                   </span> 

                   <!--| WP <span class="glyphicon glyphicon-tag"> </span>-->

                   <br>

                   <?php for( $i = 1; $i <= $model->prioridad; $i++){ ?>
                      <a href="javascript:void(0)" onclick="prioridad(<?= $i ?>)"><span class="glyphicon glyphicon-star gold"></span></a>
                  <?php } ?>
                  <?php for($i = $model->prioridad ; $i < 3; $i++){ ?>
                      <a href="javascript:void(0)" onclick="prioridad(<?= $i ?>)"><span class="glyphicon glyphicon-star-empty "></span></a> 
                  <?php } ?>

                   <!-- <span class="glyphicon glyphicon-time warning"></span>-->

                </div>

                <div class="col-sm-4">
                    <div class="pull-right">
                          <button type="button" class="btn  btn-xs" data-toggle="collapse" data-target="#collapseExample_<?= $model->id ?>" aria-expanded="false" aria-controls="collapseExample_<?= $model->id ?>">
                              <span class="glyphicon glyphicon-chevron-down"></span> 
                          </button>
                    </div>
                </div>
              </div>


                <div class="collapse" id="collapseExample_<?= $model->id ?>">
                  <div class="well">
                    
                     <?= $model->detalles ?> 
                
                                           <!--
                        <div class="alert alert-info" role="alert">Información</div>
                        <div class="alert alert-warning" role="alert">Alerta</div>
                        <div class="alert alert-danger" role="alert">Muy encuenta</div>
                    -->
                    <br>
                    <hr><br>
                    <a href="/crm/update?id=<?= $model->id ?>"
                      class="btn btn-primary btn-xs">Modificar</a>
                  </div>
                </div>

<?php } ?>

www/backend/views/crm/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use dosamigos\datepicker\DatePicker;
use yii\helpers\ArrayHelper;
use common\models\User;
use backend\models\Colaborador;
use kartik\select2\Select2;

?>

<div class="crm-oportunidades-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'nombre')->textInput()->label('Titulo') ?>

    <?= $form->field($model, 'monto',[
        'template' => '
            {label}
            <div class="input-group">
            <span class="input-group-addon" id="basic-addon1">$</span>
            {input}
            </div>
            {error}
        '
    ])->textInput() ?>
    
    <?= $form->field($model, 'etapa')->dropDownList(
                [
                    0 => 'Nueva',
                    1 => 'Estimar',
                    2 => 'Seguimiento',

                    3 => 'Trabajando',
                    4 => 'Entregar',
                    5 => 'Pendiente',
                ],           
                ['prompt'=>'Seleccione por favor']    
        ); ?>

    <?= $form->field($model, 'detalles')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'prioridad')->dropDownList(
                [
                    0 => '*',
                    1 => '**',
                    2 => '***'
                ],           
                ['prompt'=>'Seleccione por favor']    
        ); ?>

   
     <?php /* $form->field($model, 'estado')->dropDownList(
                [
                    0 => 'Negociando',
                    1 => 'Ganada',
                    2 => 'Perdida'
                ],           
                ['prompt'=>'Seleccione por favor']    
        ); */?>

  
    <?php
        echo Html::label('Cierre estimado');
            echo DatePicker::widget([
                'model' => $model,
                'attribute' => 'cierreProyectado',
                'language' => 'es',
                'clientOptions' => [
                    'autoclose' => true,
                    'format' => 'yyyy-mm-dd',
                ]
            ]);
    ?>

    <br>
    <?php
   
    $usuarios = User::find()->where(['status'=>'1'])->all();
     
        echo $form->field($model, 'encargado')
        ->dropDownList(
        ArrayHelper::map($usuarios,'id','username'),           
        [
            'prompt'=>'Encargado'
        ]    
        );
    
        echo Html::label('Cliente');
            echo Select2::widget([
                'name' => 'CrmOportunidades[cliente]',                
                'data' => ArrayHelper::map(Colaborador::find()->where(['tipo'=>1])->all(), 'id', 'nombre'),
                'value' => $model->cliente,
                'options' => ['placeholder' => 'Cliente'],
                'pluginOptions' => [
                    'tags' => true,
                    'tokenSeparators' => [',', ' '],
                    'maximumInputLength' => 10
                ],
            ]);

    ?>
    <br>
    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <div class="row">
        <div class="col">
            <?= $form->errorSummary($model); ?>
        </div>
    </div>
    <?php ActiveForm::end(); ?>

</div>

www/backend/views/crm/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model backend\models\CrmOportunidades */

$this->title = 'Create Crm Oportunidades';
$this->params['breadcrumbs'][] = ['label' => 'Crm Oportunidades', 'url' => ['panel']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="crm-oportunidades-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

www/backend/views/crm/panel.php
<?php
use kartik\sortable\Sortable;
use common\components\Moneda;
use yii\web\View;

$this->title = 'Oportunidades';
$this->params['breadcrumbs'][] = ['label' => 'CRM', 'url' => ['/crm/panel']];
//$this->params['breadcrumbs'][] = $this->title;

$tab = (isset($_SESSION['tab_crm'])) ? $_SESSION['tab_crm'] : 1;


?>
   

<div class="row">
    <div class="col-md-10">
        <h1><?= $this->title; ?></h1>
    </div>

    <div class="col-md-2"><br>
        <a class="btn btn-success" href="/crm/create">Nueva oportunidad</a>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <ul class="nav nav-tabs">
            <li class="<?= ($tab==1)?'active':'' ?>">
                <a onclick="setTab(1)" href="#panel-1" data-toggle="tab"   aria-expanded="false">Nuevas</a>
            </li>                
            <li class="<?= ($tab==2)?'active':'' ?>">
                <a onclick="setTab(2)" href="#panel-2" data-toggle="tab"   aria-expanded="false">Ganadas</a>
            </li>
            <li class="<?= ($tab==3)?'active':'' ?>">
                <a onclick="setTab(3)" href="#panel-3" data-toggle="tab"   aria-expanded="false">Lista</a>
            </li>
        </ul>
    </div> 
</div> 

        <div class="tab-content">
            <?php
                echo $this->render('panel_one',[
                    'datos'=>$datos,
                    'tab' => $tab
                ]);

                echo $this->render('panel_two',[
                    'datos'=>$datos,
                    'tab' => $tab
                ]);
                
                 echo $this->render('panel_tree',[
                    'datos'=>$datos,
                    'tab' => $tab,
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider
                ]);
                
                ?>
          
        </div><!--Tab Content-->
<script type="text/javascript">
    
    function actualizar(e){
        let ids = ''
        $(e).children('li').each(function() {
            let oportunidad = $(this).children('.opo_sort')         
            ids = ids.concat( $(oportunidad).data('id')+',' );
        });
       
        ids = ids.slice(0, -1) + '';
        etapa = $(e).data('id')

        $.ajax({
            statusCode: {
                200: function() {
                    location.reload();
                },
                304: function() {
                    console.log('error al modificar');
                }
              },
            type: 'get',
            url: "/crm/cambiar-etapa",
            data: {
                "ids":ids,
                'etapa':etapa
            }
        });


        
   }

</script>
<?php

$this->registerJsFile(
    '@web/js/crm.js',
    ['depends' => [\yii\web\JqueryAsset::className()]]
);

www/backend/views/crm/panel_one.php
<?php
use kartik\sortable\Sortable;
use common\components\Moneda;
use yii\web\View;

$etapas = [
        0=>['titulo'=>'Nueva',      'items'=>[],'total'=>0],
        1=>['titulo'=>'Estimar',   'items'=>[],'total'=>0],
        2=>['titulo'=>'Seguimiento',    'items'=>[],'total'=>0],
     //   3=>['titulo'=>'Entregar','items'=>[],'total'=>0],
    ];


foreach($datos as $oportunidad){
    if($oportunidad->etapa<3){
	    array_push($etapas[$oportunidad->etapa]['items'],
	        [
	            'content'=>$this->render('_ficha_oportunidad',
	                [
	                    'model'=>$oportunidad
	                ]),
	            'id'=>$oportunidad->id
	        ]);

	    $etapas[$oportunidad->etapa]['total'] += $oportunidad->monto;
	}
} ?>


<div class="tab-pane <?= ($tab==1)?'active':'' ?>" id="panel-1">  

                    <div class="row"> 

                    <?php
                        $conta=0;
                        foreach ($etapas as $key=>$etapa) { ?>
                            <div class="col-xs-3">
                            <h3><?= $etapa['titulo'] ?> <span class="label label-info btn-xs"><?= Moneda::gettm($etapa['total'],'$'); ?></span></h3>
                            <?php
                            echo Sortable::widget([
                                'connected'=>true,
                                'items'=>$etapa['items'],
                                'id' => 'opo_sort_'.$key,
                                'options' => [
                                    'data-id'=>$key
                                ],
                                'pluginEvents' => [
                                    'sortupdate' => '
                                    function() { 
                                        actualizar(this);
                                     }',
                                ]
                            ]);?>
                            </div>
                            <?php
                        }
                    ?>                    
                        
                    </div><!--row panel-->

                </div><!--Panel-->

www/backend/views/crm/panel_tree.php
<?php
use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\search\CrmOportunidadesSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Crm Oportunidades';
$this->params['breadcrumbs'][] = $this->title;
?>


<div class="tab-pane <?= ($tab==3)?'active':'' ?>" id="panel-3">  

    <div class="row"> 
                    
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [           
            'id',
            'nombre:ntext',
            'monto',
            'etapa',
            'detalles:ntext',
            'prioridad',
            // 'orden',
            // 'estado',
            // 'creacion',
            // 'modificacion',
             'cierreProyectado',
            // 'encargado',
             'cliente0.NombreCompleto',

            ['class' => 'yii\grid\ActionColumn',
            'template'=>'{update}'],
        ],
    ]); ?>
</div>
</div>

www/backend/views/crm/panel_two.php
<?php
use kartik\sortable\Sortable;
use common\components\Moneda;
use yii\web\View;

$etapas = [
        3=>['titulo'=>'Trabajando',      'items'=>[],'total'=>0],
        4=>['titulo'=>'Entregar',   'items'=>[],'total'=>0],
        5=>['titulo'=>'Pendiente',    'items'=>[],'total'=>0]
    ];


foreach($datos as $oportunidad){
    if($oportunidad->etapa>2){
        array_push($etapas[$oportunidad->etapa]['items'],
            [
                'content'=>$this->render('_ficha_oportunidad',
                    [
                        'model'=>$oportunidad
                    ]),
                'id'=>$oportunidad->id
            ]);

        $etapas[$oportunidad->etapa]['total'] += $oportunidad->monto;
    }
} ?>


<div class="tab-pane <?= ($tab==2)?'active':'' ?>" id="panel-2">  

                    <div class="row"> 

                    <?php
                        $conta=0;
                        foreach ($etapas as $key=>$etapa) { ?>
                            <div class="col-xs-3">
                            <h3><?= $etapa['titulo'] ?> <span class="label label-info btn-xs"><?= Moneda::gettm($etapa['total'],'$'); ?></span></h3>
                            <?php
                            echo Sortable::widget([
                                'connected'=>true,
                                'items'=>$etapa['items'],
                                'id' => 'opo_sort_'.$key,
                                'options' => [
                                    'data-id'=>$key
                                ],
                                'pluginEvents' => [
                                    'sortupdate' => '
                                    function() { 
                                        actualizar(this);
                                     }',
                                ]
                            ]);?>
                            </div>
                            <?php
                        }
                    ?>                    
                        
                    </div><!--row panel-->

                </div><!--Panel-->

www/backend/views/crm/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model backend\models\CrmOportunidades */

$this->title = 'Update Crm Oportunidades: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Crm Oportunidades', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="crm-oportunidades-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>